# Generated by Django 5.0.6 on 2024-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('leage', models.CharField(max_length=100)),
            ],
        ),
    ]
